### ISSUE TITLE
CSS inside a template ('style' tag)

### ISSUE THREAD

**Issue by brunolemos** [mquandalle/meteor-jade#102]
I used to do this to create a reactive CSS:

```html
<style type="text/css">
    #profile-bg {
        background-color: {{themeColor}};
    }
</style>
```

The closest I got with this package was this:

```jade
style
    |    body {
    |        background: red !important;
    |    }
```

But it's not nice to put a pipe in every line and I couldn't get the {{themeColor}} to work.
What is the suggested way?

Thanks.

**Comment by mquandalle** [comment]
Thank you for the bug report ! This is fixed in [v0.4.3](https://github.com/mquandalle/meteor-jade/releases/tag/v0.4.3).

**Comment by chaturangalagama** [comment]
It worked for me too. Thanks a lot mquandalle..

**Comment by thomasreinecke** [comment]
great stuff, worked for me aswell 👍
