### ISSUE TITLE
Content of Block in a Tag are escaped.

### ISSUE THREAD

**Issue by jeeeyul** [mquandalle/meteor-jade#109]
Today, I updated meteor and jade package(0.2.8 -> 0.4.1), I found some issue that is not exists before

```jade
p.
  hello <b>world</b>, {{someHelper}}
```

Should have to be rendered:
```html
<p>
  hello <b>world</b> helperResult
</p>
```

However, actual results are:
```html
<p>
  hello &lt;b&gt;world&lt;/b&gt; {{someHelper}}
</p>
```

The cases below are works correctly:
```jade
p hello <b>world</b>
p
  | hello <b>world</b>
```

**Comment by mquandalle** [comment]
Fixed in [v0.4.2](https://github.com/mquandalle/meteor-jade/releases/tag/v0.4.2).
