### ISSUE TITLE
Better option for creating extra attributes on divs?

### ISSUE THREAD

**Issue by tehfailsafe** [mquandalle/meteor-jade#114]
Looking into polymer lately, and they use a lot of semantic attributes on elements. For example, the following in jade:
`.entry(fit="", layout="", vertical="", center="", center-justified="")`

is actually more challenging than the equivalent in raw html:
`<div class="entry" layout vertical center center-justified>`

Is there a better way to write it in jade?

**Comment by mquandalle** [comment]
Yes, you can write

```jade
.entry(fit layout vertical center center-justified)
```

**Comment by tehfailsafe** [comment]
Hmm, I wasn't getting that to work, but now I am... Perhaps it was simply a misspelled attribute... Sorry!
