### ISSUE TITLE
Dead link to Components Inside Tags in README.md

### ISSUE THREAD

**Issue by nickmasso** [mquandalle/meteor-jade#115]
The webpage `https://github.com/mquandalle/meteor-jade/#components-inside-tags` doesn't exist (or at least doesn't seem to for me), but its linked to in `https://github.com/mquandalle/meteor-jade/#anonymous-helper`. Or am I missing something here?

**Comment by mquandalle** [comment]
The idea was to link #1. Please keep this issue open until I fix the link in the README.
