### ISSUE TITLE
Class name "merging" issue

### ISSUE THREAD

**Issue by kzvaigzne** [mquandalle/meteor-jade#117]
When using Semantic-UI, more specifically their grids, you can setup your grid to have different column widths based on device used(mobile, tablet, computer etc).
You do that by using class names along the lines of "two wide mobile", "six wide computer" and so on.

The issue presents itself when Jade "merges" the duplicate classnames.

For example:
`#content.sixteen.wide.mobile.twelve.wide.computer.column` which compiles to `<div id='content' class='sixteen wide mobile twelve computer column'></div>` and that means that Semantic-UIs grid definitions aren't working since they rely on class name "grouping".

I've tried using the "class" attribute: `#content(class='<grid column definition>')` but that does the same.
I've also tried importing a non-Jade(Spacebars) template but the classnames get merged anyways.

**Comment by mquandalle** [comment]
Does this bug also happen in spacebars? https://github.com/meteor/meteor/issues/3628

**Comment by kzvaigzne** [comment]
I believe when I tested, it was working with Spacebars
