### ISSUE TITLE
{{#if isInRole 'admin'}} causes jade to choke

### ISSUE THREAD

**Issue by ericchen0121** [mquandalle/meteor-jade#118]
I'm well aware of https://github.com/mquandalle/meteor-jade/issues/113 and have been diligently using {{ }} when my template handlers take arguments. 

However, I hit a new variation of this, using alanning:roles, (https://github.com/alanning/meteor-roles), the template helper requires this syntax in html, which includes an {{#if, a template helper name and some arguments.

{{#if isInRole 'admin' }}
{{#if isInRole 'admin' 'researchAndDevelopment'}}

The registered helper from alanning:roles takes one or two arguments. 

I tried every variation I could think of of this in jade, to no avail, including: 

+if (isInRole 'admin')
{{#if isInRole 'admin'}}
+if(ifInRole 'admin')
+if isInRole('admin')

I got a variety of errors, including: 
While building the application:
   client/templates/nav/_navAdmin2.jade: Jade syntax error: unexpected token "indent"
   <runJavaScript-68>:60:14: Cannot read property 'head' of undefined (compiling
   client/templates/nav/_navAdmin2.jade) (at fileModeHandler)

When inputting  `+if isInRole('admin')` in jade, this error:  
 While building the application:
   client/templates/nav/_navAdmin2.jade: Jade syntax error: The end of the string was
   reached with no closing bracket found.
   <runJavaScript-68>:60:14: Cannot read property 'head' of undefined (compiling
   client/templates/nav/_navAdmin2.jade) (at fileModeHandler)

Ultimately, I resorted to creating an HTML template specifically for this block with the {{#if isInRole 'admin'}} <BLOCK OF CODE HERE>  {{/if}} comprising the entire template, and just including this HTML template inside my jade template. 

Incredibly non-ideal, but sometimes it must be done. 

Can you shed any light on the reason why none of my attempts worked, or whether there is a fix in the works that would fix this?

Thanks!

**Comment by avalanche1** [comment]
did you try
if isInRole 'admin'

**Comment by rndD** [comment]
In my case syntax ``if someTemplateHelper arg1 arg2`` worked perfectly.

**Comment by mquandalle** [comment]
“if” + helper + argument is tested here https://github.com/mquandalle/meteor-jade/blob/51da6afc1b68e834036f4512d71a0b7537d8f063/packages/jade/tests/match.jade#L131-L137.

The fact that the test is passing mean that this template is compiled to the exact same code as the spacebars version. Are you sure the error comes from meteor-jade? If yes, please provide a minimal reproduction.
