### ISSUE TITLE
Jade filters are not supported in meteor-jade

### ISSUE THREAD

**Issue by jalavosus** [mquandalle/meteor-jade#119]
When trying to load a coffeescript file for jQuery using the following code:
<code>

    script(type='text/javascript', src="http://code.jquery.com/jquery 1.9.1.min.js")

    script(type="text/javascript", src="client/custom.coffee")

    :coffeescript

		    $(document).ready -> setDate

    div.timer_box#days

    div.timer_box#hours

    div.timer_box#minutes

    div.timer_box#seconds
</code>
Where setDate sets the html/Jade to a given amount of days/hours/minutes/seconds left until a given deadline, meteor server returns <code>Jade syntax error: Jade filters are not supported in meteor-jade on line %line% </code>

Is there any way to get around this or otherwise use coffeescript + jQuery in meteor-jade?

**Comment by mquandalle** [comment]
There is no plan to support filters in meteor-jade. If you want to write some coffeescript, just put your code on a `.coffee` file.
