### ISSUE TITLE
todos example doesnt compile

### ISSUE THREAD

**Issue by avalanche1** [mquandalle/meteor-jade#120]
How should this code look in meteor-jade?
   <ul>
      {{#each tasks}}
        {{> task}}
      {{/each}}
    </ul>
However I try, it gives me errors or a blank page

**Comment by mquandalle** [comment]
```jade
each tasks
  +task
```

**Comment by avalanche1** [comment]
Maxime, i just cant get the todos example to function. Pls, help - how this code sd look?

<body>
  <div class="container">
    <header>
      <h1>Todo List</h1>
    </header>

    <ul>
      {{#each tasks}}
        {{> task}}
      {{/each}}
    </ul>
  </div>
</body>

<template name="task">
  <li>{{text}}</li>
</template>
// simple-todos.js
if (Meteor.isClient) {
  // This code only runs on the client
  Template.body.helpers({
    tasks: [
      { text: "This is task 1" },
      { text: "This is task 2" },
      { text: "This is task 3" }
    ]
  });
}

**Comment by mquandalle** [comment]
Please take a look at the documentation.
