### ISSUE TITLE
meteor 1.0.4: Template.subscriptionsReady doesn't work

### ISSUE THREAD

**Issue by ndemoreau** [mquandalle/meteor-jade#123]
This doesn't seem to work:

            if Template.subscriptionsReady
                ready
            else
                Loading... 

Any idea why?

**Comment by sunstorymvp** [comment]
<pre><code>template(name='foo')
  if subscriptionsReady
    ready
  else
    Loading...
</code></pre>

<pre><code>Template.foo.helpers
  subscriptionsReady: ->
    Session.get 'subscriptionsReady'

Template.foo.onRendered ->
  Session.set 'subscriptionsReady', false

  @autorun =>
    subscribeParams = {}
    @subscribe 'collection', subscribeParams,
      onError: ->
        Session.set 'subscriptionsReady', false
      onReady: ->
        Session.set 'subscriptionsReady', true
</code></pre>

**Comment by DenisGorbachev** [comment]
Better register a helper:

```coffeescript
UI.registerHelper "subscriptionsReady", ->
  Template.instance().subscriptionsReady()

**Comment by sunstorymvp** [comment]
it's better, but Template.subscriptionsReady == Template.instance().subscriptionsReady() and it is not working properly

**Comment by mquandalle** [comment]
As showed in the above test, `Template.subscriptionsReady` compiles to the same code in meteor-jade and in spacebars. Maybe you forgot to add a `|` in front of your tests?
