### ISSUE TITLE
problems when upgrading to meteor 1.0.5

### ISSUE THREAD

**Issue by jaredtmartin** [mquandalle/meteor-jade#124]
I'm not sure, but I think its a jade issue.  Here's the error:
```
TypeError: undefined is not an object (evaluating 'Template.__body__.__contentParts.push')
```

Here's my jade file:
```jade
head
  title Health Marketplace
  meta(name="viewport" content="width=device-width, initial-scale=1.0" http-equiv="X-UA-Compatible")
body
  +activeScreen
```
Here's my helper:
```js
UI.body.helpers({
  activeScreen:function(){
    return Template[Session.get('activeScreen')];
  },
});
```

I went back and forth with git and I've narrowed it down to upgrading to Meteor 1.0.5 from Meteor 1.0.2.
Perhaps I'm doing something wrong? Was something deprecated?

**Comment by mquandalle** [comment]
What version of jade are you using?

**Comment by jaredtmartin** [comment]
My sincerest apologies.  It turns out, I had two problems: 
First, I **wasn't** using your jade package, I was using cryptoquick:jade. Switching to your package solved the problem.  I didn't notice this cause it was an older project and all my new projects use your package.

The second problem seems to be in the mrt:accounts-ui-bs3-and-blaze package.  Given the name, it's probably long due for an update.  Switching to ian:accounts-ui-bootstrap-3 removed the second error.

For the record, both packages gave me the error above, so each time I refreshed, I would get the error above twice.

Thanks a lot for providing your package and keeping it running!
