### ISSUE TITLE
How would this syntax be used in Meteor jade?

### ISSUE THREAD

**Issue by sferoze** [mquandalle/meteor-jade#125]
How to convert this

```
{{#transitioner}}
  {{> yield}}
{{/transitioner}}
```

To be used with Meteor jade? 

if templates are integrated with `+yield' 

then how exactly are spacebar variable with # handled? 

Also can you mix spacebars and jade? For instances where there is no spacebar alternative?

**Comment by mquandalle** [comment]
```jade
+transitioner
  +yield
```
