### ISSUE TITLE
Value={{something}}

### ISSUE THREAD

**Issue by sangyoo91** [mquandalle/meteor-jade#129]
`textarea#submit-content(value='{{content}}')`

this will not return my values..

Any workaround?

**Comment by mquandalle** [comment]
The textarea tag in HTML doesn't have a `value` attribute (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea):

```jade
textarea#submit-content= content
```

**Comment by sangyoo91** [comment]
Ah... I did not know this! I was converting my app to jade and im surprised that textarea value had been working as i had expected it to even when it did mot exist. Interesting :)
