### ISSUE TITLE
The tag name provided is not a valid name.

### ISSUE THREAD

**Issue by avalanche1** [mquandalle/meteor-jade#134]
I'm trying to insert percolate:momentum helper into a jade template:
```Jade
#{momentum plugin='right-to-left'}
	if show
		h2 About me
```
.. and get an error in console on file materializer.js:
*Uncaught InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('momentum plugin='right-to-left'') is not a valid name.*

While native spacebars syntax works fine:
```Handlebars
	{{#momentum plugin='right-to-left'}}
		{{#if show}}
		<h2> About me</h2>
		<p>My text!</p>
		{{/if}}
	{{/momentum}}
```

**Comment by mquandalle** [comment]
The meteor-jade syntax would be:

```jade
+momentum(plugin='right-to-left')
    if show
        h2 About me
```

**Comment by avalanche1** [comment]
ok, that works, thank you)
but as i read from the docs '+' sign goes for:  'If you want to include a template inside another,
precede its name by the + symbol'
Reading further there is the Components section... but for me it was not obvious that it's talking about custom block helpers.
Maybe rename Components -> Custom block helpers?
