### ISSUE TITLE
how to use server-side jade-compiler

### ISSUE THREAD

**Issue by mrzafod** [mquandalle/meteor-jade#138]
Hi, are there any examples on how to compile ```.jade``` on server side. I am going to response custom html content for search bots.

**Comment by mquandalle** [comment]
Hello @mrzafod,

You can either use `meteorhacks:meteor-ssr` (which support jade templates), or directly use the JadeCompiler API:

```sh
meteor add mquandalle:jade-compiler
```

and then

```js
JadeCompiler.compile('h1 hello world');
```
