### ISSUE TITLE
More troubles with pathFor

### ISSUE THREAD

**Issue by lustrousgorilla** [mquandalle/meteor-jade#144]
I've found #10, #84, and #131 but still running into issues.

Using the same example as @sferoze...

Given a route:
```coffee
Router.route '/posts/_:id',
  name: 'postPage'
  data: ->
    Posts.findOne @params._id
```

And the template:
```jade
a.discuss.btn.btn-default(href="{{pathFor 'postPage'}}") Discuss
```

The href attribute is disappearing entirely, but this time his fix of modifying
```jade
href="{{pathFor 'postPage'}}"
```
to
```jade
href="{{pathFor 'postPage' _id=this._id}}"
```
doesn't help.

**Comment by mquandalle** [comment]
Hello,

I'm pretty sure this is not a problem with meteor-jade (the template syntax) but instead with blaze or iron-router.

**Comment by lustrousgorilla** [comment]
Thanks for such a quick response. I think you're right. I tried swapping it out jade for spacebars to no avail.
