### ISSUE TITLE
head.tpl.jade

### ISSUE THREAD

**Issue by sibeliusseraphini** [mquandalle/meteor-jade#150]
head.tpl.jade is not recognized as template(name="head")

I tried this jade:

    template(name="head")
      head
      meta(charset="utf-8")
      meta(http-equiv="X-UA-Compatible", content="IE=edge")
      meta(name="viewport", content="width=device-width, initial-scale=1")
      meta(name="description", content="")
      meta(name="author", content="")
      title Website

**Comment by dalgard** [comment]
I can spot a few mistakes:

- You shouldn't put your `head` inside a template. The common pattern is to create a file called `index.jade` or `head.jade`, which contains the markup *without* the `template` element.
- The elements under `head` are not properly nested in your example – they should be indented another level.
- The point of  the `.tpl.jade` extension is that you don't have to write `template(name='...')`. Don't use this extension for your `head` file, though.

**Comment by sibelius** [comment]
thanks, sorry to not reply soon
