### ISSUE TITLE
Template names cannot have dashes

### ISSUE THREAD

**Issue by kopasetik** [mquandalle/meteor-jade#156]
Otherwise you get this error
While building the application:
   [filename-redacted].jade: Jade syntax error: Expected identifier, number, string, boolean, or null
   {{>ssq-Navbar }}
   ^
   packages/compileJade/plugin/handler.js:54:1: Cannot read property 'head' of undefined (compiling [filename-redacted].jade) (at fileModeHandler) 

Sample code:
head
  title meteor-sitsquare
body
  +ssq-Navbar
template(name='sellStep1')
  // Photo
  // Just title for now... actual photo/camera stuff coming later
  h1 PHOTO
  form.step1
    p
      input(type='text', name='itemTitle', placeholder='Title')
    p
      button.nextStep Next
template(name='sellStep2')
  // Details
  h1 DETAILS
  form.step2
    p
      input(type='text', name='itemDesc', placeholder='Description')
    p
      button.nextStep Next
template(name='sellStep3')
  // Price
  h1 PRICE
  form.step3
    p Enter the price
    p
      input(type='text', name='itemPrice', placeholder='Price')
    p
      button.nextStep Next
template(name='sellStep4')
  // Finish
  h1 FINISH
  p
    button.nextStep Next
template(name='ssq-Navbar')
  nav.navbar.navbar-default
    .container-fluid
      // Brand and toggle get grouped for better mobile display
      .navbar-header
        button.navbar-toggle.collapsed(type='button', data-toggle='collapse', data-target='#bs-example-navbar-collapse-1', aria-expanded='false')
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand(href='#') Brand
      // Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          li.active
            a(href='#')
              | Link 
              span.sr-only (current)
          li
            a(href='#') Link
          li.dropdown
            a.dropdown-toggle(href='#', data-toggle='dropdown', role='button', aria-haspopup='true', aria-expanded='false')
              | Dropdown 
              span.caret
            ul.dropdown-menu
              li
                a(href='#') Action
              li
                a(href='#') Another action
              li
                a(href='#') Something else here
              li.divider(role='separator')
              li
                a(href='#') Separated link
              li.divider(role='separator')
              li
                a(href='#') One more separated link
        form.navbar-form.navbar-left(role='search')
          .form-group
            input.form-control(type='text', placeholder='Search')
          button.btn.btn-default(type='submit') Submit
        ul.nav.navbar-nav.navbar-right
          li
            a(href='#') Link
          li.dropdown
            a.dropdown-toggle(href='#', data-toggle='dropdown', role='button', aria-haspopup='true', aria-expanded='false')
              | Dropdown 
              span.caret
            ul.dropdown-menu
              li
                a(href='#') Action
              li
                a(href='#') Another action
              li
                a(href='#') Something else here
              li.divider(role='separator')
              li
                a(href='#') Separated link
      // /.navbar-collapse
    // /.container-fluid

**Comment by ericwangqing** [comment]
+1
A lots of our templates need to be naming with dash inside

**Comment by ericwangqing** [comment]
It turns out that's not a problem with meteor-jade but meteor itself https://github.com/meteor/meteor/issues/1602

**Comment by dalgard** [comment]
Please close the issue.
