### ISSUE TITLE
body.tpl.jade.js outputs "attr(undefined)" without attributes

### ISSUE THREAD

**Issue by timche** [mquandalle/meteor-jade#159]
I keep getting this error in the console

```
Uncaught TypeError: Cannot read property 'nodeType' of undefined
  jQuery.extend.attr @ jquery.js:7941
  jQuery.access @ jquery.js:4176
  jQuery.fn.extend.attr @ jquery.js:7928
  (anonymous function) @ body.tpl.jade.js?bf6a27f449a5d25e475d7265e88b37879c4deb7f:2
  runStartupCallbacks @ startup_client.js:30
  ready @ startup_client.js:32
```

because `body.tpl.jade.js` has a undefined attribute:

```
Meteor.startup(function() { 
  $('body').attr(undefined); 
});
```

My body.tpl.jade:

```
body
  +sAlert
```

How can I avoid this error or stop meteor-jade from creating a undefined attribute?

**Comment by dalgard** [comment]
+1

(You're not supposed to include a root element like `<body>` inside your Jade file, when it has the extension `.tpl.jade` – but that shouldn't be what's causing the error.)

**Comment by dalgard** [comment]
It works if you just call the file `body.jade`, although the docs pretty much say that it should work with `body.tpl.jade`, without the `body` tag inside the file.

**Comment by ferhtgoldaraz** [comment]
It's happening to me too, `body.jade`with the body tag is working, as commented

**Comment by dalgard** [comment]
I've modified a fork of this package that adds some useful features and also fixes this bug in version `0.5.4`. The fork has been released as [dalgard:jade](https://github.com/dalgard/meteor-jade).

I will keep the new package in sync with the original, should there be any updates, and generally continue maintenance until, hopefully, the two packages can be merged.

(The error, btw, was this comparison: `attrs !== {}`. Objects are passed by reference, so this will always be true, even if the `attrs` object is empty.)

**Comment by talha-asad** [comment]
@mquandalle can we get this bug fixed?

**Comment by rdooh** [comment]
@dalgard and @mquandalle - maybe some PR action etc?

**Comment by femans** [comment]
+1

**Comment by mquandalle** [comment]
Is this still an issue?
