### ISSUE TITLE
ReferenceError: Npm is not defined

### ISSUE THREAD

**Issue by renanlecaro** [mquandalle/meteor-jade#168]
Steps to reproduce :

- `meteor create repeat-jade-bug`
- `cd repeat-jade-bug`
- `meteor add mquandalle:jade-compiler`
- `meteor`
- go to localhost:3000
- open the console : "Uncaught ReferenceError: Npm is not defined. "

It looks like the problem is in "mquandalle_jade-compiler.js" line 47
The crash prevents the front end to start alltogether.

My setup seems up to date.
`meteor update`
`This project is already at Meteor 1.1.0.3, the latest
release.`
`Your packages are at their latest compatible versions.`

I don't have the knowledge to fix it, i'm quite new to meteor. Maybe it's not even a bug. Am I missing something ? 

I was using the jade template engine for the client side views without problems. Now i'm trying to use jade for ssr of email body and i get this.

**Comment by edmundkwok** [comment]
I'm facing the same issue. Some background:

* I am using _mquandalle:jade_ for client side templates
* Now I want to use _meteorhacks:ssr_ to render Jade templates. When attempting to render, it throws this error:
```
Error: Unknown language: jade at Error () at Object.SSR.compileTemplate
```
* Looking at _meteorhacks:ssr_ source / issue queue, it seems to be reading from _mquandalle:jade-compiler_ for Jade templates.
* Adding _mquandalle:jade-compiler_ makes SSR work, but client side templates won't load anymore
* Tried playing around with the load order of the packages but still no joy
