### ISSUE TITLE
Meteor 1.2 Issues

### ISSUE THREAD

**Issue by sangyoo91** [mquandalle/meteor-jade#169]
`METEOR@1.2-rc.11`

I don't know why but ever since I have updated it to `1.2-rc.11`, jade doesn't recover from errors (I have to end up restarting the server again).

**Comment by dalgard** [comment]
I'm not experiencing this. Is this still and issue in Meteor version `1.2.0.2`?

**Comment by sangyoo91** [comment]
@dalgard I haven't noticed it in a while. I should've paid close attention to when the problem disappeared.

**Comment by dalgard** [comment]
If you can confirm at some point that the problem's gone, the issue can be closed.

**Comment by sangyoo91** [comment]
@dalgard I'll close the issue for now since I haven't experienced it in a while. I'll reopen the issue if the problem re-occurs with more detailed information.
