### ISSUE TITLE
Using the dynamic named route helper in Iron Router with Jade

### ISSUE THREAD

**Issue by sferoze** [mquandalle/meteor-jade#17]
When defining a route with an :_id field using iron-router

``` coffee
  @route 'postPage',
    path: '/posts/:_id'
    data: -> 
      Posts.findOne @params._id
```

and adding the route into the jade page like so:

``` jade
    a.discuss.btn(href="{{pathFor 'postPage'}}") Discuss
```

does not work. What happens is jade just gets rid of the whole href attribute and the button does not link to anywhere. In the html there is no more href attribute. It is supposed to put in the path for the postPage + id of the post appended. 

It seems like an issue with the path having an _id field in it. When I remove the _id filed, it puts in the correct route but I need the _id field for dynamic routing

UPDATE:

I found a way to make it work, like this:

``` jade
a.discuss.btn(href="{{pathFor 'postPage' _id=this._id}}") Discuss 
```

But I in the book Discover Meteor, it says Iron router should automatically detect that the route specified requires an id field, so it checks the data context in the spot it is located and adds the _id field if neccessary. So 
1)

``` jade
    a.discuss.btn(href="{{pathFor 'postPage'}}") Discuss
```

is equivalent to
2)

``` jade
  a.discuss.btn(href="{{pathFor 'postPage' _id=this._id}}") Discuss 
```

Using the second way works right now but the first method does not.

**Comment by picsoung** [comment]
Quite curious to see how it would work today using Handlebar.

I am trying to have 

`<a href="{{pathFor route='index' query='search={{name}}' }}">{{name}}</a>`
