### ISSUE TITLE
Use a helper in head title

### ISSUE THREAD

**Issue by thomasarbona** [mquandalle/meteor-jade#170]
Hi,
I'm trying to use my `title` helper in my `<head>`, this is my helper:
```js
Template.registerHelper("title", function () {
    return Router.current().data().title;
});
```
And this is how I use it:
```jade
head
	title #{title}
```
I've tried a lot of other forms for use the helper at this place, but always the same error:
```
=> Errors prevented startup:

   While building the application:
   packages/htmljs/visitors.js:326:1: Unexpected object in htmljs in toHTML: [object Object] (compiling
   client/templates/application/head.jade)
   at [object Object].HTML.ToHTMLVisitor.def.visitObject (packages/htmljs/visitors.js:326:1)
   at [object Object].HTML.Visitor.def.visit (packages/htmljs/visitors.js:61:1)
   at [object Object].HTML.ToHTMLVisitor.def.visitTag (packages/htmljs/visitors.js:309:1)
   at [object Object].HTML.Visitor.def.visit (packages/htmljs/visitors.js:46:1)
   at [object Object].HTML.ToHTMLVisitor.def.visitArray (packages/htmljs/visitors.js:261:1)
   at [object Object].HTML.Visitor.def.visit (packages/htmljs/visitors.js:59:1)
   at Object.HTML.toHTML (packages/htmljs/html.js:239:1)
   at fileModeHandler (packages/compileJade/plugin/handler.js:57:1)
```
I hope you can help me, thank you in advance.

**Comment by adamwong246** [comment]
+1

**Comment by SoullessWaffle** [comment]
+1

**Comment by dalgard** [comment]
I doubt that the helper you are trying to use is available, when `<head>` is compiled, but am not sure. It is not the recommended way to set title, anyway. Instead, create an `autorun` that depends on the route and sets the title programmatically.

There may a better place to put this code, but this illustrates it:

```js
Meteor.startup(function () {
  // Reactively update the page title
  Tracker.autorun(function () {
    document.title = Router.current().data().title;
  });
});
```

You might consider not keeping the title in the router data context, but instead update it with a helper in each template. I've used this pattern with success earlier:

```jade
template(name='foo')
  //- Use dalgard:jade or Spacebars syntax here
  #{pageTitle 'This is foo'}
```

```js
Template.registerHelper("pageTitle", function (title) {
  document.title = title;
});
```

**Comment by mquandalle** [comment]
:+1: for @dalgard answer. Generally speaking this is an issue with the runtime engine (Blaze) not with the meteor-jade syntax — ie Spacebars has exactly the same issue, see for instance https://github.com/meteor/meteor/issues/266

**Comment by delueg** [comment]
this iron-router SEO package worked for me: https://github.com/DerMambo/ms-seo
