### ISSUE TITLE
using jade with angular-meteor causes flex attribute to become flex="flex"

### ISSUE THREAD

**Issue by mattiLeBlanc** [mquandalle/meteor-jade#177]
Hi,

I am working on an angular+meteor project using the package `civilframe:angular-jade` to enable ng.jade templates.
This package is using this Jade package for compiling.
Anyway, I noticed that when `ng.jade` is converted it tends to change the single attributes without value.
```
div(flex) Foo
```
becomes
```
<div flex="flex">Foo</div>
```
It should just stay 
```
<div flex>Foo</div>
```
because Angular Materials is tripping over this. It doesn't know flex="flex" and turns into class="flex-flex" :)

Is there an easy fix to not convert attributes that are without value?

**Comment by mquandalle** [comment]
I’m not sure I understand, isn’t that an issue with `civilframe:angular-jade`?

**Comment by mattiLeBlanc** [comment]
Well, I think meteor-jade creates the `flex="flex"` attributes, right?
If so, it shouldn't it compile it as 'flex' or 'flex=""' ?
Angular-Jade package only calls your compile function, hence I thought the issues should be posted here.

**Comment by mquandalle** [comment]
No meteor-jade doesn’t compile to `flex="flex"`. It compiles to `<div flex>Foo</div>` (as displayed on the Chrome debuggers tools) or `<div flex="">Foo</div>` (as displayed in the Firefox debuggers tools). This part is actually handled by Blaze (the runtime engine), all we do ensure is that `div(flex) Foo` in meteor-jade will do the same thing as `<div flex>Foo</div>` in Spacebars.

Do you have a link to point where `civilframe:angular-jade` actually call `JadeCompiler`?

**Comment by mattiLeBlanc** [comment]
I thought it was here:
`https://github.com/civilframe/meteor-angular-jade/blob/master/plugin.js#L11`

**Comment by mquandalle** [comment]
Well no, this `jade` comes from NPM not `mquandalle:meteor-jade`. I encourage you to open an issue at https://github.com/civilframe/meteor-angular-jade

**Comment by mattiLeBlanc** [comment]
okay, sorry for the confusion. I thought you where the Jade master :)
