### ISSUE TITLE
each x in y loop

### ISSUE THREAD

**Issue by mquandalle** [mquandalle/meteor-jade#18]
Currently we use `each` to loop over a list or a cursor. `each` works by setting the context (`this`) to the current element inside the block of content. If you want to access a variable outside of this context you have to use the `../` notation.

For some cases this may be a non-intuitive syntax. For instance consider a table where each cell has a `x` and an `y` coordinate. Currently we would do:

```js
Template.table.helpers({size: _.range(10)});
```

```jade
template(name="table")
  table
    each size
      tr
        each size
          td #{..} #{.}
```

It would be more natural to use a `for element in list` loop to avoid the dot notation:

```jade
template(name="table")
  table
    for x in size
      tr
        for y in size
          td #{x} #{y}
```

Any thought?

**Comment by mquandalle** [comment]
Yah! The original idea here was to make a hack to transpile a `for/each x in y` into a simple `each x` that is the only form supported by blaze by playing with contextual hierarchy (`../../`).

But this transpiler hack will not be necessary thanks to the upcoming support for this feature in spacebars/blaze. See https://github.com/meteor/meteor/pull/3560. Thank you very much @slava for this great initiative :-)

I'll ensure that this feature gets proper support in meteor-jade until it gets officially released.

**Comment by mquandalle** [comment]
@tagrudev So it will be called `each x in y` not `for x in y`, my original idea was to not conflict with the core component, but that's not needed anymore.

**Comment by Slava** [comment]
Well, I hit some issues implementing it, see the issue. It might take a while to support it correctly.

**Comment by mquandalle** [comment]
But the only fact that you are willing to support this feature is comforting, I was never excited about the AST transformation hack I originally proposed.

**Comment by filipstachura** [comment]
Any updates on this one?
