### ISSUE TITLE
Package Conflict: {this} and rubaxa:sortable

### ISSUE THREAD

**Issue by AlbinoGeek** [mquandalle/meteor-jade#182]
Hello,

This package currently is incompatible with `rubaxa:sortable` simply because a custom context-block handler with an end-tag is not supported in Jade, even if the end-tag is left out.  Please see the following HTML required to make the package work, that is not reproducible in meteor-jade.

```html
{{#sortable items=items options=options}}
  {{ListItem}}
{{/sortable}}
```

The closest Jade would be (but does not compile):
```jade
+sortable(items=items, options=options)
  +ListItem
```

I have also tried with brackets, as well as with/without an end-tag.

---

### Found Workaround

You can work around this issue by defining your sortables in a non-jade file (raw .html template) and including that template inside a Jade template, note that this should not be considered a passable solution as this pollutes the application.

---

If this is **not-a-bug** then please tell me the correct Jade syntax to use a custom block handler, as this is not the only package that uses custom block handlers that doesn't work inside of `meteor-jade`.

**Comment by mquandalle** [comment]
You should remove the comma in the jade version.

**Comment by AlbinoGeek** [comment]
```jade
  .ui.divided.selection.list
    +sortable(animation='300' items=stories options=options sortField='order')
      +ProjectStoryEstimateListItem
```

Thank you, this works.

---

Can you please tell me why this goes against argument syntax?  All arguments must be comma separates lists elsewhere in meteor-jade and in Meteor.  I suppose this is because this only turns into a simple spacebars function call under the hood, yes?

**Comment by mquandalle** [comment]
Yes you have guessed correctly. `meteor-jade` is syntactic sugar targeting Blaze, and a lot of things that work in vanilla jade (but don’t in Spacebars or Blaze) won’t work in it.
