### ISSUE TITLE
not like Jade

### ISSUE THREAD

**Issue by pixelass** [mquandalle/meteor-jade#184]
while you are stating that is basically like Jade you are confusing developers.

```jade
div hello world
```
is valid Jade but will not work with your package

```
div class = "foo"
```

is not valid Jade but will work with your package

```jade
mixin hello(name)
  div hello #{name}
```

or 

```jade
mixin hello(name)
  div 
    | hello #{name}
```

will break meteor although it is a jade feature

```
while counter--
  div
```

is valid Jade but will not work with your package.

I could keep going but I guess you get the picture

I think you should consider removing the line 

> Meteor-jade basically works like pure Jade [...]

And highlight the fact that you are using the lexer but did major adjustments so most of Jades native features will not work.

It is only fair.

**Comment by pixelass** [comment]
please note:  I'm not saying this is a "bad" package, I'm only saying you are selling it as something that it isn't.

**Comment by AlbinoGeek** [comment]
@pixelass Many of these features rely on #1 which is that `meteor-jade` does not implement the Jade lexer's inline JavaScript support, which allows it to do just about anything that you can't do with this package (yet.)  Follow that bug report, and the pull request #176 here for more information on the progress.

**Comment by pixelass** [comment]
@AlbinoGeek that is no explanation. Please read what I'm really asking here.

> Meteor-jade basically works like pure Jade, so if you never use Jade before you should take a look at the documentation.

...is a misleading statement. If I look at the Jade documentation I expect the features above to work. This package has very little to do with Jade. It simply "looks" similar. That's all I'm saying. The statement should be removed (since it is wrong) or a more honest explanation should be chosen.

**Comment by mquandalle** [comment]
I’m a non-native english speaker/writer, and I have probably used the word “basically” to mean “have a basic understanding” back when I created this package 2 years ago. I will accept I pull request that improve my prose.

**Comment by AlbinoGeek** [comment]
@mquandalle Fair enough on that :).

@pixelass Ahh, yeah.  Working on fixing that though, hence why I said to have a look at #1 and the discussion around the pull request (yes, there's a PR currently on the code feature working.)  Some of the things you noted might actually be bugs too.

**Comment by pixelass** [comment]
@mquandalle I'll be glad to write a little text/tutorial for you and open a PR. You can then modify it to your needs. It's really only about making this a more valid statement. It's 4:30 AM here (probably not a good time for that) but I might be able to do it a little later today. Otherwise It will have to wait a week because I' m on a conference next week.

**Comment by AlbinoGeek** [comment]
@pixelass Is this solved now?

**Comment by pixelass** [comment]
I guess the term "somewhat" describes it better, yes. I might add/remove a few things and send a PR when I get back home.
