### ISSUE TITLE
#{jade} expression not working in some cases 

### ISSUE THREAD

**Issue by caglarcem** [mquandalle/meteor-jade#189]
Not sure if it's relavant but I used iron-cli jade less scaffolding.

This works fine (pls follow the "greeting"):
```jade
template(name='hello')
   h1 Lending Library #{greeting}
   #content
      input(type='button',value='Click')
```

This doesn't work:
```jade
template(name='hello')
   h1 Lending Library 
   #content
      #{greeting}
      input(type='button',value='Click')
```

This (spacebars) works fine:
```jade
template(name='hello')
   h1 Lending Library 
   #content
      {{greeting}}
      input(type='button',value='Click')
```

**Comment by talha-asad** [comment]
maybe if add a ```|``` before ```#{greeting}``` otherwise jade will render it as a tag ?

**Comment by mquandalle** [comment]
Yes it’s either

```jade
#content
  | {{greeting}}
```

or

```jade
#content
  = greeting
```

**Comment by caglarcem** [comment]
Thanks a bunch both! 

wonder if it's worth adding to the front page doco..

**Comment by mquandalle** [comment]
Feel free to improve the documentation and send a PR ;-)

**Comment by caglarcem** [comment]
Kinda new to open source, good to know I can do that :) will do, cheers!
