### ISSUE TITLE
Using AutoformModal

### ISSUE THREAD

**Issue by orozcorp** [mquandalle/meteor-jade#191]
I am trying to use autoform Modal with Jade
https://atmospherejs.com/yogiben/autoform-modals

How can I write the following

{{#afModal class="btn btn-primary" collection="Posts" operation="update" doc=_id}}
  Update post
{{/afModal}}

**Comment by mquandalle** [comment]
```jade
+afModal(class="btn btn-primary" collection="Posts" operation="update" doc=_id)
  | Update post
```

**Comment by orozcorp** [comment]
On Thu, Nov 5, 2015 at 3:33 PM, Maxime Quandalle <notifications@github.com>
wrote:

> +afModal(class="btn btn-primary" collection="Posts" operation="update" doc
> =_id)


Thanks a lot


-- 
----------------------------------------------------
Eduardo Orozco Mendoza
See the magical in the mundane!
