### ISSUE TITLE
Autoform (afFieldInput) throwing errors

### ISSUE THREAD

**Issue by Acostan** [mquandalle/meteor-jade#192]
Hi,

Could you tell me what I'm doing wrong here. The input box renders, but doesn't apply the class or other attributes. 

https://github.com/Acostan/test-autoform-jade
```
+afFieldInput name="Email" id="Email" type="text" placeholder="Enter email ..." class="form-control"
```

In addition, its throwing these errors, which is preventing the from from submitting:

Exception in template helper: TypeError: Cannot read property 'label' of undefined
    at Object.afFieldInputContext (http://localhost:3000/packages/aldeed_autoform.js?019cba9c67d18d17c34ea48a455d8956ded05487:7119:53)

Exception in template helper: TypeError: Cannot read property 'class' of undefined
    at Object.addClass (http://localhost:3000/packages/aldeed_autoform.js?019cba9c67d18d17c34ea48a455d8956ded05487:515:20)

**Comment by fa7ad** [comment]
try with parentheses again maybe?

**Comment by Acostan** [comment]
The issue was that my +autoForm collection="" was undefined. Once the collection argument was valid, then the form rendered correctly.
