### ISSUE TITLE
Any idea how to translate this to jade?

### ISSUE THREAD

**Issue by andregoldstein** [mquandalle/meteor-jade#193]
```
{{#html5Dropzone class="media-cover" hoverClass="hover" unhoverClass="unhover"}}
p Content in here
{{/html5Dropzone}}
```

This is from the  [meteor-html5-dropzone package](https://github.com/hockeyj85/meteor-html5-dropzone) and is the only thing I've not managed to figure out a way of translating to jade without breaking things.

Any ideas?

**Comment by mquandalle** [comment]
```jade
+html5Dropzone(class="media-cover" hoverClass="hover" unhoverClass="unhover")
  p Content in here
```

**Comment by andregoldstein** [comment]
@mquandalle Thanks so much. that works great, not sure how I missed trying it that way works perfectly!
