### ISSUE TITLE
What happens now that Jade is renaming to Pug?

### ISSUE THREAD

**Issue by KyleKing** [mquandalle/meteor-jade#198]
I just found out about this today when I was looking for a Jade linter. Source: https://github.com/pugjs/jade/issues/2184

**Comment by antoniobrandao** [comment]
What a bad new name.

**Comment by mabubaker1947** [comment]
A very Bad name at all, Pug sounds like a Pug Dog.....

**Comment by antoniobrandao** [comment]
Worse name ever... Even worse considering the previous name was really awesome.

**Comment by mattiLeBlanc** [comment]
So, what do we do? (besides whining about the name). Actually, the name is quite ridiculous. I will hate looking at .pug files for the rest of eternity.
Can't we come up with something else? Like Trump? template.trump looks cool.
(joking of course)

**Comment by PascalPixel** [comment]
Hi, wondering why you haven't renamed yet for the beta? 2.0.0 is a big overhaul and will need a lot of work.
The rename was done due to jade being trademarked and legal action being threatened.

**Comment by KyleKing** [comment]
Unfortunately, there is a lot more than just renaming the package. There would be many breaking changes from the file extension to the rewritten code and syntax changes. At this point, it might be best to create a new fork that supports the Pug framework and moving people towards that. I don't know if @mquandalle has chimed in yet. See https://github.com/pugjs/pug/issues/2305 and [2.0 roadmap](https://github.com/pugjs/pug/milestones/2.0.0%20-%20Modules%20and%20Plugins)

I'd be happy to help support the update

**Comment by hems** [comment]
+1 for pug and blaze jazziness!

**Comment by hems** [comment]
@mquandalle i guess closing this issue that means there is no plan to update to the new version?

**Comment by mquandalle** [comment]
Yes, sorry I'm not using this package anymore
