### ISSUE TITLE
Template names starting with _

### ISSUE THREAD

**Issue by talha-asad** [mquandalle/meteor-jade#199]
Create a template file, such as `_test.tpl.jade`. This template cannot be included using `+_test` but instead with `+test`. Looks like a bug.

@mquandalle is this, being done on purpose?

**Comment by mquandalle** [comment]
No, I would merge a PR fixing that.

**Comment by talha-asad** [comment]
Okay please assign this the bug label and i will try and fix this.

**Comment by talha-asad** [comment]
Can you give me a pointer, where i should start working on this? I am now testing it with a standard meteor html template, just to make sure this is not being caused by meteor itself.

**Comment by mquandalle** [comment]
The template name is calculated [here](https://github.com/mquandalle/meteor-jade/blob/5a435b364b44a5c742d23d574d2e71479b5009cc/packages/jade/plugin/handler.js#L92).

**Comment by talha-asad** [comment]
Thanks.

**Comment by talha-asad** [comment]
Okay this works fine with Meteor simple html templates. I am going to try and fix this in your package.

**Comment by mquandalle** [comment]
I think you also need to add `_` to the regex that detects “user-components” [here](https://github.com/mquandalle/meteor-jade/blob/5a435b364b44a5c742d23d574d2e71479b5009cc/packages/jade-compiler/lib/lexer.js#L35).

**Comment by talha-asad** [comment]
Yes makes sense, thanks.

**Comment by talha-asad** [comment]
Sorry @mquandalle. Seems this works already, it wasn't working for me as i renamed a bunch of template names to start with `_` and apparently meteor didn't recompile the spacebar version of it. So the bug is maybe that. And the component regex probably needs to support template names starting with `_`.

**Comment by mquandalle** [comment]
Ok, I understand the issue, will work on a fix.

**Comment by mquandalle** [comment]
Actually underscores are already supported (from the `\w` symbol in the regex), so it is only a problem of cache invalidation when you renamed your jade files.

**Comment by talha-asad** [comment]
Makes sense. Thanks for the quick fix :+1:
