### ISSUE TITLE
FlowRouter isReady with Jade

### ISSUE THREAD

**Issue by humbertocruz** [mquandalle/meteor-jade#202]
Hello, I want to use {{#if isReady "subs"}} on my template using jade then I trying 

if isReady "subs"

but it's do no works with the message: Error: No such function: isReady

how should I do that ?
thanks

**Comment by mikeifomin** [comment]
@humbertocruz  
[Use](https://www.discovermeteor.com/blog/template-level-subscriptions/#template.subscriptionsready) `Template.subscriptionsReady` 

Here is an example:

``` jade
template(name="dashboardWidget")
  if Template.subscriptionsReady
    p Your content
  else
    h3 Content is loading
```

An Inline Handlebars-Jade example:

``` jade
.header(class="{{#if Template.subscriptionsReady}} ready{{/if}}")

```
