### ISSUE TITLE
leave each or if and increase ident

### ISSUE THREAD

**Issue by humbertocruz** [mquandalle/meteor-jade#205]
Hello, there is a way to leave or close a each and in the next line, ident a level ? example:

if isSelected
  div.selected
else
  div
h3 div content

in this example the h3 tag will be outside the div

thanks

**Comment by mquandalle** [comment]
The canonical way to write that would be:

``` jade
div(class="{{#if isSelected}}selected{{/if}}")
  h3 div content
```
