### ISSUE TITLE
Repeated classes removed

### ISSUE THREAD

**Issue by humbertocruz** [mquandalle/meteor-jade#206]
Hello,

I'm using Jade with MeteorJS and the "incredible" Semantic-UI. Today I noticed that the jade compiler is removing the repeated classes of the elements. This should be ok but not for the semantic ui, for example:

div.ui.middle.aligned.center.aligned.grid

the second aligned class is removed and the div is not "center aligned"

there is any way the avoid that ? a jade config {remove.repeated.classes:false} por example ?

Thanks

**Comment by Dartv** [comment]
This is not related to jade compiler but to Meteor itself. There was an issue about this https://github.com/Semantic-Org/Semantic-UI/issues/1526
