### ISSUE TITLE
Usage with Autoform?

### ISSUE THREAD

**Issue by CinderHub** [mquandalle/meteor-jade#22]
I seem to be having some troubles getting autoform working with Jade, would love to be able to use both. Writing something like this: +autoForm(schema=signupFormSchema,type="method",meteormethod= "signupUser")
+afFieldInput(name="Username")
returns an "Expected space ...ema= signupFormSchema, type= "method"" error. Is using autoform possible with Jade? If so, I guess I'll just have to dig harder then. I'll keep poking at it either way.

**Comment by Acostan** [comment]
Can anybody tell me why this isn't working?
Reference Issue: https://github.com/mquandalle/meteor-jade/issues/192

**Comment by rikyperdana** [comment]
@CinderHub I follow you way but it's not working on my codes
+autoForm class="coverForm" schema=signupFormSchema type="insert"
+afFieldInput class="coverFormInput" name="username"
Only the old way {{#autoForm}}{{/autoForm}} works
