### ISSUE TITLE
mixin support

### ISSUE THREAD

**Issue by dweldon** [mquandalle/meteor-jade#53]
I'm about to migrate a large project using jade (compiled outside of meteor) over to using this package. We use mixins in a few places. My assumption is that mixins are not and will not be supported (and will need to be converted to templates) is that the case?

**Comment by Pushplaybang** [comment]
I think this would be particularly useful in situations where iron-router layouts require similar blocks.  

For instance, I have a home layout, app layout and admin layout, all of them require a hidden modal block that I keep hidden which contains a `+yield "modal"` wrapped in some basic markup.  

It would be awesome to be able to only have to define that once.

**Comment by daithi-coombes** [comment]
+1 from me.

For prototyping and mocking up I think this would be a handy feature to have to reduce my dev time.
