### ISSUE TITLE
Inline if-statements

### ISSUE THREAD

**Issue by myknbani** [mquandalle/meteor-jade#70]
Is it possible to do something like this in meteor-jade?

```
<template name="fontAwesomeIcon">
    <i class="fa fa-{{icon}} {{#if large}}fa-lg{{/if}} fa-fw"></i>
</template>
```

**Comment by RobertLowe** [comment]
Awesome, this is totally nicer.

**Comment by nickmasso** [comment]
Is there a reason you can't do this? (It doesn't seem to be working for me.)

    i.fa(class="fa-#{icon} #{#if large}fa-lg#{/if}")

**Comment by cseelus** [comment]
Inline conditional statements seem not to work like with regular Jade. I get a `Jade syntax error: Expected identifier, number, string, boolean, or null` when I try something [like this](http://stackoverflow.com/a/14144327/973852) …

```jade
div#demo.collapse(class=typeof fromEdit === "undefined" ? "" : "in")
```

[or this](http://stackoverflow.com/a/14319011/973852):

```jade
div(class=(i===0 ? 'span13' : 'span13 offset3'))
```

**Comment by mquandalle** [comment]
@cseelus Yes, unfortunately we don't support “Javascript expressions” — that's a Blaze limitation. The idea is that you will be able to do the same things in meteor-jade and spacebars, and inline conditional statements are not yet possible in spacebars.

**Comment by cseelus** [comment]
@mquandalle Thanks for the clarification
