### ISSUE TITLE
How to use jade when creating your own package?

### ISSUE THREAD

**Issue by lowi** [mquandalle/meteor-jade#83]
I am writing my own package, and I would like to use jade for the templates.
Is it possible? What dependency should I add?

**Comment by Nesvet** [comment]
I've spent a couple of hours trying to make it work. That's what I need:
```
api.use([
	"templating",
	"mquandalle:jade@0.4.1"
], "client");
```
Without specifying the version, I've always got ```0.1.0```. Why?

**Comment by mquandalle** [comment]
@Nesvet I have no idea. The constraint solving is handled by meteor and I don't think this package can do anything to solve that.

**Comment by KristerV** [comment]
hey I've just stumbled on this very issue and specifying the version helps a lot.. What a headache.

**Comment by KristerV** [comment]
sorry, to be more specific I had the same problem as Nesvet and the version lock fixes the issue.

**Comment by mquandalle** [comment]
@KristerV Feel free to propose a PR explaining that in the README.md documentation.

**Comment by KristerV** [comment]
ok, here it is. #136

**Comment by mquandalle** [comment]
Related: https://github.com/meteor/meteor/issues/4170
