### ISSUE TITLE
divs are not concatenated

### ISSUE THREAD

**Issue by timothyarmes** [mquandalle/meteor-jade#86]
Input such as this:

div Content
div Content

should produce this (if jade pretty output is off, which it is by default)

&lt;div&gt;Content&lt;/div&gt;&lt;div&gt;Content&lt;/div&gt;

However, the result appears to insert whitespace:

&lt;div&gt;Content&lt;/div&gt; &lt;div&gt;Content&lt;/div&gt;

That whitespace means that if we use this Jade package, it's impossible to fight the space between inline block elements :(

http://css-tricks.com/fighting-the-space-between-inline-block-elements/

**Comment by Geen-Henk** [comment]
Sorry for the necro, but I've encountered a similar issue. One that is only solved by using the inline literals (which doesn't make it really readable) or using an `each`.

Desired effect:

![Desired effect](https://cloud.githubusercontent.com/assets/7933750/7110668/c7563444-e1b5-11e4-86f5-e0b38362b1a2.png)

However using any of the following setups gives me whitespace, breaking the 33.333% width of the `li`s:

```jade
//- Normal Jade, expected to work
.filter-options
  ul.tabs.tabs-3
    li.tab(data-tab="#one").active One
    li.tab(data-tab="#two") Two
    li.tab(data-tab="#three") Three
```

```jade
//- Using __noNewLine__
.filter-options
  ul.tabs.tabs-3
    li.tab(data-tab="#one").active One
    li.tab(data-tab="#two") __noNewLine__Two
    li.tab(data-tab="#three") __noNewLine__Three
```

```jade
//- Inline literals on own line (for readability)
.filter-options
  ul.tabs.tabs-3
    | #[li.tab(data-tab="#one").active One]
    | #[li.tab(data-tab="#two") Two]
    | #[li.tab(data-tab="#three") Three]
```

All of these produce the following:

![image](https://cloud.githubusercontent.com/assets/7933750/7110738/9b542ef4-e1b6-11e4-84cf-4f6b270cec03.png)

The strange thing is, that when I use an `each` statement, the whitespace is omitted:

```jade
//- Each statement, `filterTabs` being a helper
.filter-options
  ul.tabs.tabs-3
    +each filterTabs
      +if active
        li.tab(data-tab=name).active=caption
      +else
        li.tab(data-tab=name)=caption
```

This makes it much more complicated than needed, having to define a helper which doesn't change, just for whitespace issues.
