### ISSUE TITLE
pre. broke

### ISSUE THREAD

**Issue by ManuelDeLeon** [mquandalle/meteor-jade#92]
pre. used to work like the html counterpart, in that it accepted html code inside, e.g. in plain old html the following block:
```
<pre>
  <p>&gt;<b>This</b> is a paragraph.</p>
</pre>
```

would come out as:
<pre>
  <p>&gt;<b>This</b> is a paragraph.</p>
</pre>

pre. used to work like that but it now escapes the blocks, i.e. &amp;gt; doesn't output >

**Comment by sylido** [comment]
I was having trouble with the inline bracket tags in text as well `#[div hello]` doesn't seem to work.
Was it supported before `pre` broke ?

**Comment by ManuelDeLeon** [comment]
yep, it worked fine on 0.2.9

**Comment by mquandalle** [comment]
Hello Manuel,

I'm sorry it took so long but this bug should finally be fixed in v0.4.2 :-)

**Comment by ManuelDeLeon** [comment]
SWEET!
Don't worry about it, I know you have a life =)
Thanks for the fix.
